inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/**/*'
    - 'app/helpers/*' 

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'lib/tasks/dev.rake'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/**/*'
 

## 日本語コメントを許可します。
Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  
Style/BlockComments:
  Enabled: false
  
Style/RedundantFetchBlock:
  SafeForConstants: false

Style/SymbolArray:
  EnforcedStyle: brackets  

Style/PercentLiteralDelimiters:
  Enabled: false 
  
## クラス名をネストさせずコンパクトに記述できるように
Style/ClassAndModuleChildren:
  EnforcedStyle: compact  
  Exclude:
    - 'app/channels/**/*'


Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true  

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: empty_lines

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false  

## クラス名の最初と最後に空の行をつける
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

## １行の長さ
Layout/LineLength:
  Max: 150  


Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true 

Lint/EmptyBlock:
  AllowComments: true   


Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'Guardfile'
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'app/views/**/*.jbuilder'
    - 'lib/tasks/dev.rake'

Rails/HelperInstanceVariable:
  Enabled: true 